version: "2"
linters:
  default: none
  enable:
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    lll:
      line-length: 197
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/makkes)
        - Prefix(github.com/makkes/garage)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
