linters:
  disable-all: true
  enable:
    - gci
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - prealloc
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  lll:
    line-length: 197
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/makkes)
      - Prefix(github.com/makkes/garage)
